-- # 05b_seed_company_config.sql
-- 🛠️ นำข้อมูลกฎและระเบียบเดิม (Local Mock Data) กลับคืนสู่ Supabase Database

UPDATE public.company_configs
SET 
  rules = '[{"id":"rule-general","order":1,"title":"กฎระเบียบทั่วไป (General Rules)","content":"พนักงานทุกคนต้องปฏิบัติตามกฎระเบียบอย่างเคร่งครัด เพื่อรักษามาตรฐานการทำงานและวัฒนธรรมองค์กรที่ดี\n\n- วันทำงานคือวันจันทร์ - อาทิตย์ (หากไม่มีการแจ้งล่วงหน้า)\n- การลางานต้องแจ้งล่วงหน้าอย่างน้อย 24 ชั่วโมงผ่านระบบปฏิทิน\n- ห้ามนำข้อมูลลูกค้าหรือข้อมูลเพจไปเผยแพร่ภายนอกโดยไม่ได้รับอนุญาต","category":"General","lastUpdated":"2026-03-28T09:48:37.136Z"},{"id":"rule-responsibilities","order":2,"title":"หน้าที่รับผิดชอบ (Responsibilities)","content":"- หาฟุตเทจ ตัดต่อคลิปสั้น (Reels/Shorts) ความยาว 1-5 นาที\n- แทรกแบนเนอร์โฆษณาลงคลิปตามรูปแบบที่กำหนด\n- โพสต์ลงเพจ Facebook / Social Media ที่ได้รับมอบหมาย (ดูแลขั้นต่ำ 10 เพจ)","category":"Operation","targetRoles":["Staff","Manager","Super Admin"],"lastUpdated":"2026-03-29T07:59:40.349Z"},{"id":"rule-submissions","order":4,"title":"กฎระเบียบการส่งงาน (Submissions)","content":"พนักงานต้องส่งงานผ่านระบบ \"ส่งคลิปงานรายวัน\" ทุกวันทำงาน\n\n- จำนวนขั้นต่ำ: 10 เพจ / วัน\n- จำนวนคลิป: 4 คลิป / เพจ (รวม 40 คลิป/วัน)\n\n⚠️ หากส่งไม่ครบถ้วนตามกำหนด ระบบจะถือว่าขาดงาน (Absent)","category":"Compliance","targetRoles":["Staff","Manager","Super Admin","Developer"],"lastUpdated":"2026-03-29T08:13:00.637Z"},{"id":"rule-commission","order":4,"title":"โครงสร้างค่าคอมมิชชัน (Commission)","content":"- Tier 1 (Standard): 1,000 THB ต่อยอดวิวทุก 10,000,000 Views\n- Tier 2 (Super Bonus): 1,500 THB ต่อยอดวิวทุก 10,000,000 Views (เมื่อครบ 100M)","category":"Finance","targetRoles":["Staff","Manager","Super Admin","Developer"],"lastUpdated":"2026-03-29T08:13:00.637Z"},{"id":"rule-penalties","order":5,"title":"กฎการหักเงิน (Penalties)","content":"หากยอดวิวรวม (Views) ของพนักงานในเดือนนั้น ไม่ถึงเกณฑ์ขั้นต่ำ (10,000,000 Views) จะมีมาตรการหักเงินเดือน -2,000 THB\n\n- หยุดงานหักตามค่าแรง เช่น 12,000 หยุดหัก 400\n\n- ส่งงานไม่ครบ 40 คลิปต่อวันหัก 20 บาท/คลิป\n\n- ส่งลิงก์ซ้ำหัก 50 บาท/คลิป\n\nหากขาดงานจะถูกหักเป็น 2 แรง","category":"Safety","targetRoles":["Staff","Manager","Super Admin","Developer"],"lastUpdated":"2026-03-29T08:13:00.637Z"},{"id":"rule-culture","order":6,"title":"วัฒนธรรมองค์กร (Culture)","content":"เราเน้นการทำงานที่รับผิดชอบตนเองเป็นหลัก (High Responsibility) และการวัดผลด้วยความสำเร็จ (Result-Oriented)\n\nCore Values: Honesty, Transparency, Prosperity","category":"General","lastUpdated":"2026-03-28T09:48:37.136Z"}]'::jsonb,
  holidays = '[{"id":"h-nye","date":"12-31","name":"วันสิ้นปี","multiplier":2,"isRecurring":true},{"id":"h-nyd","date":"01-01","name":"วันขึ้นปีใหม่","multiplier":2,"isRecurring":true},{"id":"h-labour","date":"05-01","name":"วันแรงงานแห่งชาติ","multiplier":2,"isRecurring":true},{"id":"h-sk1","date":"04-13","name":"วันสงกรานต์","multiplier":2,"isRecurring":true},{"id":"h-sk2","date":"04-14","name":"วันสงกรานต์","multiplier":2,"isRecurring":true},{"id":"h-sk3","date":"04-15","name":"วันสงกรานต์","multiplier":2,"isRecurring":true}]'::jsonb,
  groups = '[{"id":"news","name":"กลุ่มข่าวสาร","policy":{"groupId":"news","minPagesPerDay":5,"minClipsPerPage":8},"isDefault":false},{"id":"shows","name":"กลุ่มรายการ","policy":{"groupId":"shows","minPagesPerDay":10,"minClipsPerPage":4},"isDefault":true}]'::jsonb,
  brands = '[{"id":"brand-1774793169256","name":"USE99","isActive":true},{"id":"brand-1774793206352","name":"IF888","isActive":true},{"id":"brand-1774793218627","name":"UFA257","isActive":true},{"id":"brand-1774793221874","name":"ZEED777","isActive":true}]'::jsonb
WHERE id = 'core-config';
